### ISSUE TITLE
What is "porn"?

### ISSUE THREAD

**Issue by sergzach** [bakwc/PornDetector#13]
Hello. 

I'm sorry, but on my tests your porn detector works with insufficient quality. For instance, it often recognizes an image with girl face and lips as porn. Porn images could be easily found in the Internet. How did you check your quality - are you sure that your training set did not consist of mainly porn? You should train on also non-porn images which are near to be porn: girls' faces and necks, swimsuits, etc. Now it seems your classifier recognizes if there are some 'nude' places on an image.

On the other hand, what is porn? There is no strict definition. Naked genitals? Probably it is more close idea to use naked genitals to recognize them. It seems that you used too broad definition.

**Comment by bakwc** [comment]
I used very small dataset - there is regular people in negative samples, but not too much. You can train your own dataset. Read #8 thread - there is some usefull information about improving quality.

**Comment by sergzach** [comment]
Thank you. It's quite difficult sometimes to obtain right data to train.

One more question. Can your model get some additional parameters, for example, confidence of prediction? I think it could be useful.

**Comment by bakwc** [comment]
Currently we calculate prediction with `predictions = tf.argmax(y_conv, 1)` You can use for example `tf.reduce_max` to get the exact value - that will be confidence.

**Comment by sergzach** [comment]
Thank you!
