### ISSUE TITLE
Keep getting an index error.

### ISSUE THREAD

**Issue by Rich700000000000** [bakwc/PornDetector#2]
I keep getting this index error:

```
Traceback (most recent call last):
      File "pcr.py", line 335, in <module>
        train()
       File "pcr.py", line 291, in train
       positiveFiles, negativeFiles, testFiles = loadFileLists()
      File "pcr.py", line 283, in loadFileLists
        print testFiles[0], negativeFiles[0], positiveFiles[0]
    IndexError: list index out of range
```

Without doing anything.

**Comment by bakwc** [comment]
Fixed. It was a training code that tried to load a training data-set. Now you can try to launch:
./pcr.py url http://example.com/img.jpg
PS. If you have some problems with cv SIFT, look at http://stackoverflow.com/questions/18561910/opencv-python-cant-use-surf-sift

**Comment by xiangzhai** [comment]
> PS. If you have some problems with cv SIFT

we should report the bug to Linux distribution packagers!
