### ISSUE TITLE
Suggestion: Possible Rename? 

### ISSUE THREAD

**Issue by Rich700000000000** [bakwc/PornDetector#5]
Before I start, I want to make it clear that I have absolutely no moral compunctions about porn: I'm neither a christian nor a misandrist. 

However, I would really like to add my GitHub to my resume, and I assume you would too. Could you consider another name, like "ExplicitExactor" or something along those lines?

I've been studying Theano, and I would love to fork this project, but the name might raise eyebrows in a bad way.  

This is just a suggestion of course, It's still all your code.

**Comment by Rich700000000000** [comment]
If I'm out of line here, don't hesitate to correct me.

**Comment by bakwc** [comment]
Hm.. I'l think about it.

**Comment by Rich700000000000** [comment]
I promise, I'm not trying to censor you.

**Comment by bakwc** [comment]
Don't think it's a good idea. The whole project implemented and tested on porn images, the neural network architecture was adopted specially for this task. Also don't see any issues with mention this in CV (I already mentioned in my linkedin, recruiters regulary sending me offers).
