### ISSUE TITLE
IndexError: unsupported iterator index

### ISSUE THREAD

**Issue by genki** [bakwc/PornDetector#6]
I have tried to train the nnpcr and it caused error like this

```
% ./nnpcr.py train
[2016-09-14 18:50:24,652 nnpcr.py:243 INFO]  loading dataset
Traceback (most recent call last):
  File "./nnpcr.py", line 293, in <module>
    pcr.train()
  File "./nnpcr.py", line 244, in train
    trainX, trainY, testX, testY = loadDataset()
  File "./nnpcr.py", line 103, in loadDataset
    trainY = denseToOneHot(np.array(trainY), 2)
  File "./nnpcr.py", line 92, in denseToOneHot
    labels_one_hot.flat[index_offset + labels_dense.ravel()] = 1
IndexError: unsupported iterator index
```

**Comment by bakwc** [comment]
It seems like no images loaded. You need to create three directories: `1` (with non-porn images), `2` (with porn images), `cache` (empty). And remove old cache file if exists, `nncache.bin`.

**Comment by genki** [comment]
Thank you for response.
But I have those 3 dirs. Each of "1" and "2" has 1 jpeg image file.
Umm...

**Comment by bakwc** [comment]
Do you removed `nncache.bin` ?

**Comment by bakwc** [comment]
BTW, one image is not enough for training model. You need at least few thousands.

**Comment by genki** [comment]
I prepared 100 images for each dirs then got it works :)
