### ISSUE TITLE
.Pb file ?

### ISSUE THREAD

**Issue by Enxyphered** [bakwc/PornDetector#9]
You have provided a .bin file... If I do graph.Import(""//Path to .bin file); will it work ?
Note that I am using TensorFlowSharp but I have previously used the inceptionmodel.pb and inceptionmodel_label.txt to get outputs... I was just wondering if there'll be a difference when using a bin file

**Comment by Enxyphered** [comment]
Yeah so I got an Invalid GraphDef Exception... How do I take your bin file and convert it into a .pb graphDef ???

**Comment by bakwc** [comment]
bin file is not a model graph, it's a model state. If you need model graph - you should call tf.train.write_graph() inside saveModel function (line 284)
